"""empty message

Revision ID: 8bfe66cb7af7
Revises: 
Create Date: 2024-12-17 22:14:32.216620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfe66cb7af7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('cookie_id', sa.String(length=255), nullable=False),
    sa.Column('Q1', sa.Integer(), nullable=False),
    sa.Column('Q2', sa.Integer(), nullable=False),
    sa.Column('Q3', sa.Integer(), nullable=False),
    sa.Column('Q4', sa.Integer(), nullable=False),
    sa.Column('Q5', sa.Integer(), nullable=False),
    sa.Column('Q6', sa.Integer(), nullable=False),
    sa.Column('Q7', sa.Integer(), nullable=False),
    sa.Column('Q8', sa.Integer(), nullable=False),
    sa.Column('Q9', sa.Integer(), nullable=False),
    sa.Column('Q10', sa.Integer(), nullable=False),
    sa.Column('Q11', sa.Integer(), nullable=False),
    sa.Column('Q12', sa.Integer(), nullable=False),
    sa.Column('Q13', sa.Integer(), nullable=False),
    sa.Column('Q14', sa.Integer(), nullable=False),
    sa.Column('Q15', sa.Integer(), nullable=False),
    sa.Column('Q16', sa.Integer(), nullable=False),
    sa.Column('Q17', sa.Integer(), nullable=False),
    sa.Column('Q18', sa.Integer(), nullable=False),
    sa.Column('Q19', sa.Integer(), nullable=False),
    sa.Column('Q20', sa.Integer(), nullable=False),
    sa.Column('Q21', sa.Integer(), nullable=False),
    sa.Column('Q22', sa.Integer(), nullable=False),
    sa.Column('Q23', sa.Integer(), nullable=False),
    sa.Column('Q24', sa.Integer(), nullable=False),
    sa.Column('Q25', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cookie_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('participants')
    # ### end Alembic commands ###
